
all:
	bash run-ips-mat-mul-demo-N.sh 666
#	bash run-ips-mat-mul-demo-plot.sh ips-mat-mul-demo-N.log

run:
	bash run-ips-mat-mul-demo-400..1400.sh
	bash ips-mat-mul-demo-plot.sh

pack:
	tar czvf ips-mat-mul-demo1.tar.gz *.c *.sh Makefile *.log

